---
run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - goheader
    - goimports
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    #- wrapcheck ORKA
    - wsl
issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - errorlint
        - gocyclo
        - err113
        - wrapcheck
        - dogsled
        - gosec
  exclude-files:
    - ".*.gen.go"
  exclude-dirs:
    - bin
    - cmd
    - generated
linters-settings:
  dupl:
    threshold: 200
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G101
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
  wrapcheck:
    ignorePackageGlobs:
      - customerpb/*
