# This workflow deletes the previous pre-release.

on:
  workflow_call:

name: Pre-Release-Delete

jobs:
  Pre-Release-Delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.ref }}

      - name: Get latest pre-release
        id: latest-prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "version=$(gh api -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/releases \
            | jq --raw-output 'map(select(.prerelease)) | first | .tag_name // ""')" >> "$GITHUB_OUTPUT"

      - name: Delete previous pre-release
        if: ${{ steps.latest-prerelease.outputs.version != '' }}
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: gh release delete ${{ steps.latest-prerelease.outputs.version }} --yes
