# This workflow creates a release by creating a changelog from the
# conventional commit messages.

on:
  workflow_call:
    inputs:
      prerelease:
        required: true
        type: boolean

name: Release

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Get latest released tag
        id: latest-released-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "version=$(gh api -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases/latest \
            | jq --raw-output '.tag_name // ""')" >> "$GITHUB_OUTPUT"

      - name: Create changelog
        env:
          PREVIOUS_TAG: ${{ steps.latest-released-tag.outputs.version }}
        run: ./scripts/conventional-commits/change-log.sh > CHANGELOG.md

      - name: Create release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('CHANGELOG.md', 'utf8');

            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: '${{ github.ref_name }}',
              tag_name: '${{ github.ref_name }}',
              body: content,
              prerelease: ${{ inputs.prerelease }},
            })
