# This workflow creates a semantic version tag using conventional commits.

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

name: Tag

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8.0.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.version }}',
              sha: context.sha
            })
