# This workflow fetches the version that will be created for the specific commit.

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.Version.outputs.version }}
        description: "The semantic version tag that will be created for the specific commit."

name: Version

jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-version.outputs.version }}
    steps:
      # Setup environment
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{ github.sha }}

      - name: Get version
        id: semantic-version
        run: echo "version=$(scripts/conventional-commits/version.sh)" >> "$GITHUB_OUTPUT"

      - name: Print version
        run: echo "Set version to ${{ steps.semantic-version.outputs.version }}"
